# permissions for end users to edit korgijobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korgijob-editor-role
rules:
- apiGroups:
  - korgi.korgi.grycap.upv.es
  resources:
  - korgijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korgi.korgi.grycap.upv.es
  resources:
  - korgijobs/status
  verbs:
  - get
