# permissions for end users to view korgijobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korgijob-viewer-role
rules:
- apiGroups:
  - korgi.korgi.grycap.upv.es
  resources:
  - korgijobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - korgi.korgi.grycap.upv.es
  resources:
  - korgijobs/status
  verbs:
  - get
