---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - korgi.korgi.grycap.upv.es
  resources:
  - korgijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korgi.korgi.grycap.upv.es
  resources:
  - korgijobs/finalizers
  verbs:
  - update
- apiGroups:
  - korgi.korgi.grycap.upv.es
  resources:
  - korgijobs/status
  verbs:
  - get
  - patch
  - update
