# permissions for end users to view korgijobschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: korgijobscheduler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: korgi
    app.kubernetes.io/part-of: korgi
    app.kubernetes.io/managed-by: kustomize
  name: korgijobscheduler-viewer-role
rules:
- apiGroups:
  - es.upv.grycap
  resources:
  - korgijobschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.upv.grycap
  resources:
  - korgijobschedulers/status
  verbs:
  - get
