apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod-2g
spec:
  containers:
  - name: sleep-container
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/mig-2g.12gb: 1
