apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod-1g-second
spec:
  containers:
  - name: sleep-container
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/mig-1g.6gb: 1
