apiVersion: batch/v1
kind: Job
metadata:
  name: tf-cancernet-1024-1g-bs256
spec:
  template:
    metadata:
      name: tf-cancernet-1024-1g-bs256
    spec:
      volumes:
        - name: data-volume
          hostPath:
            path: /hdd500/data
            type: ''
      containers:
        - name: tf-cancernet
          image: esparig/tf-cancernet:latest
          command: 
            - /bin/bash
            - '-c'
            - >-
              python3
              training.py 
              --epochs=100
              --batch_size=256
              --learning_rate=1e-2
              --save=output/model.h5
          resources:
            limits:
              nvidia.com/mig-1g.6gb: '1'
          volumeMounts:
            - name: data-volume
              mountPath: /data
      restartPolicy: Never
