apiVersion: es.upv.grycap/v1
kind: KorgiJob
metadata:
  name: tf-cancernet-tensorboard-test
  namespace: test-nm
spec:
  image: esparig/tf-cancernet:latest
  command: 
    - /bin/bash
    - '-c'
    - >-
      python3
      training.py
      --TB 
      --epochs=3
      --batch_size=64
      --learning_rate=1e-2
      --save=output/model.h5
  korgijobscheduler: korgijobscheduler-sample
