# Simple DL Training using Tensorflow
apiVersion: batch/v1
kind: Job
metadata:
  name: job-test-2-gpus

spec:
  backoffLimit: 2
  template:
    metadata:
      name: job-test-2-gpus

    spec:
      containers:
      - name: tf-gpu-models
        image: esparig/testing-tf-models:latest
        command: ["/bin/bash","-c","cd /usr/local/lib/python3.6/dist-packages/official && python3 vision/image_classification/mnist_main.py --model_dir=$MODEL_DIR --data_dir=$DATA_DIR --train_epochs=20 --download"]
        resources:
          limits:
            nvidia.com/gpu: 2 # requesting 2 GPU
      restartPolicy: Never
